---
apiVersion: v1
kind: Pod
metadata:
  name: ungsw-mesa-build-env
spec:
  containers:
  - name: pod-mesa-base
    image: artifacts-aws.devops.microchip.com:7996/ung/mesa/mesa-build-env@sha256:6f83b517b7684f7f67a427c38a74874f64d55f978ad1c2f9093cbd2fc1d4a36c
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: '2'
        memory: 4Gi
      limits:
        cpu: '2'
        memory: 4Gi
