---
apiVersion: v1
kind: Pod
metadata:
  name: ungsw-mesa-build-env
spec:
  containers:
  - name: pod-mesa-build
    image: artifacts-aws.devops.microchip.com:7996/ung/mesa/mesa-build-env@sha256:cf1b6e3890b97d8ff80833fbc6137f321308764c18abb6806d63594fdc664d4c
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: '30'
        memory: 60Gi
      limits:
        cpu: '30'
        memory: 60Gi
